language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: k+DEY/rTQHmcbjcEQrATzQDUcnlGpE8oA6FG6+vMTGve70Dfcx24IzrfOgU0Zwi8XmpBdcUx2wEcOPgPeYUu8ZsTe3yfEuS7wt2OU1qFsyJusem7BBtB3dpXnQbrvOJiI+nYyk7bpRXvdQntO//gtYqVLN5f5P5AR8xMzttfqwiO1zofdgKAIK82tAwLfFY1xGJ/52TJdMAikrhqvoBBEP1sPAluR0JDAAKmOtjyro385CEZKC9Lw3AIAMkfXAvwMqxMinZI5ph2o+0YSzPUZcjd9AXzmEMwaV9XOpxqLcvBBuUt9opP4NNOvYUVwKFOjSfe7M/EoYmjQNChRoasZ09p+UZg63I9VkG4Ooau3xswNcSv5SXwQISD4du75zYAGJNMP/VwVh3D8Dw3T7a9oGNSnQOfGHXK0dGQIosf0FFnNqC6YNE/Vb8dTTx34SaDaDRMW51znDh/NBNk6i3dD4kmO3OyLcVJkNdGLiAJfYx+gbbjLv0v03zWe64G5qUz4xlVQby2QXWREDDPlVvRdu6Yxiyet0fVYP0l4ZIRPnWPV6QRKeHSZmoxFuGAGs7e3iUaUgYWKT8lylCdZUxO30KATlV8AX7IezzWM2nRNTQ8Q6DELr6jI/JY1zdflmeoN9fyG2q8pMgnBIwAQj0wmiEDinng7qEtdu4SXeKwRCw=
  file:
    - "to-vfile.js"
    - "to-vfile.min.js"
  on:
    tags: true
    node: '9.0'
